<a href="https://colab.research.google.com/github/rakshamishra54/sql_analytics_notebooks/blob/main/SQL_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
from google.colab import drive
import sqlite3, pandas as pd, shutil, os

drive.mount('/content/drive')

DRIVE = '/content/drive/MyDrive/'
LOCAL = '/content'


def run(query, conn):

    return pd.read_sql(query, conn)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [49]:
df = pd.read_csv(f'{DRIVE}/Retail_Sales_Analytics.csv')

In [50]:
df = df.rename(columns={'quantiy': 'quantity'})

retail = sqlite3.connect(f'{LOCAL}/retail.db')
df.to_sql('retail_sales', retail, if_exists='replace', index=False)

print(run("SELECT COUNT(*) AS rows_loaded FROM retail_sales", retail))
run("SELECT * FROM retail_sales LIMIT 5", retail)

   rows_loaded
0         2000

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantity,price_per_unit,cogs,total_sale
0,180,2022-11-05,10:47:00,117,Male,41.0,Clothing,3.0,300.0,129.0,900.0
1,522,2022-07-09,11:00:00,52,Male,46.0,Beauty,3.0,500.0,145.0,1500.0
2,559,2022-12-12,10:48:00,5,Female,40.0,Clothing,4.0,300.0,84.0,1200.0
3,1180,2022-01-06,08:53:00,85,Male,41.0,Clothing,3.0,300.0,129.0,900.0
4,1522,2022-11-14,08:35:00,48,Male,46.0,Beauty,3.0,500.0,235.0,1500.0

In [51]:
run("""
SELECT * FROM retail_sales
WHERE transactions_id is NULL

""" ,retail)

Empty DataFrame
Columns: [transactions_id, sale_date, sale_time, customer_id, gender, age, category, quantity, price_per_unit, cogs, total_sale]
Index: []

In [52]:
run("""
SELECT * FROM retail_sales
WHERE age IS NULL
   OR quantity IS NULL
   OR price_per_unit IS NULL
   OR cogs IS NULL
   OR total_sale IS NULL
""", retail)

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantity,price_per_unit,cogs,total_sale
0,432,2022-03-10,11:31:00,17,Female,NaN,Electronics,2.0,500.0,190.00,1000.0
1,1367,2022-04-15,11:38:00,16,Female,NaN,Electronics,1.0,50.0,15.50,50.0
2,1391,2022-03-01,11:29:00,130,Male,NaN,Beauty,2.0,25.0,9.25,50.0
3,1432,2022-12-25,06:24:00,67,Female,NaN,Electronics,2.0,500.0,245.00,1000.0
4,150,2022-04-13,08:25:00,89,Female,NaN,Electronics,4.0,30.0,16.20,120.0
5,845,2022-10-27,10:12:00,25,Male,NaN,Clothing,1.0,500.0,145.00,500.0
6,1150,2022-08-22,10:04:00,77,Female,NaN,Electronics,4.0,30.0,10.20,120.0
7,1845,2022-05-24,07:06:00,94,Male,NaN,Clothing,1.0,500.0,185.00,500.0
8,797,2022-09-16,06:38:00,116,Male,NaN,Clothing,3.0,25.0,10.75,75.0
9,921,2022-09-28,09:34:00,101,Male,NaN,Electronics,3.0,25.0,8.00,75.0
10,679,2022-08-26,08:59:00,64,Female,18.0,Beauty,NaN,NaN,NaN,NaN
11,746,2022-07-05,11:33:00,42,Female,33.0,Clothing,NaN,NaN,NaN,NaN
12,1225,2022-02-02,09:51:00,137,Female,57.0,Beauty,NaN,NaN,NaN,NaN

####Data exploration

In [53]:
##Write a SQL query to retrieve all columns for sales made on '2022-11-05
run("""
SELECT *
FROM retail_sales
WHERE sale_date = '2022-11-05';
""" , retail)

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantity,price_per_unit,cogs,total_sale
0,180,2022-11-05,10:47:00,117,Male,41.0,Clothing,3.0,300.0,129.00,900.0
1,240,2022-11-05,11:49:00,95,Female,23.0,Beauty,1.0,300.0,123.00,300.0
2,1256,2022-11-05,09:58:00,29,Male,23.0,Clothing,2.0,500.0,190.00,1000.0
3,1587,2022-11-05,20:06:00,140,Female,40.0,Beauty,4.0,300.0,105.00,1200.0
4,1819,2022-11-05,20:44:00,83,Female,35.0,Beauty,2.0,50.0,13.50,100.0
5,943,2022-11-05,19:29:00,90,Female,57.0,Clothing,4.0,300.0,318.00,1200.0
6,1896,2022-11-05,20:19:00,87,Female,30.0,Electronics,2.0,25.0,30.75,50.0
7,1137,2022-11-05,22:34:00,104,Male,46.0,Beauty,2.0,500.0,145.00,1000.0
8,856,2022-11-05,17:43:00,102,Male,54.0,Electronics,4.0,30.0,9.30,120.0
9,214,2022-11-05,16:31:00,53,Male,20.0,Beauty,2.0,30.0,8.10,60.0
10,1265,2022-11-05,14:35:00,86,Male,55.0,Clothing,3.0,300.0,111.00,900.0

In [54]:
##Write a SQL query to retrieve all transactions where the category is 'Beauty' and the quantity sold is more than 4 in the duration of '2022-11-01'  '2022-11-30'

run("""
SELECT*
FROM retail_sales
WHERE category ='Beauty'
AND quantity >=4
AND sale_date BETWEEN '2022-11-01' AND '2022-11-30'
""" , retail)

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantity,price_per_unit,cogs,total_sale
0,1932,2022-11-08,07:07:00,96,Female,45.0,Beauty,4.0,25.0,6.25,100.0
1,1587,2022-11-05,20:06:00,140,Female,40.0,Beauty,4.0,300.0,105.00,1200.0
2,1510,2022-11-20,18:21:00,124,Female,39.0,Beauty,4.0,50.0,19.00,200.0
3,597,2022-11-01,19:29:00,84,Male,22.0,Beauty,4.0,300.0,111.00,1200.0
4,832,2022-11-13,17:25:00,106,Male,47.0,Beauty,4.0,500.0,600.00,2000.0
5,1516,2022-11-09,17:19:00,54,Male,30.0,Beauty,4.0,25.0,24.50,100.0

In [55]:
##Write a SQL query to retrieve all transactions where the category is 'Clothing' and the quantity sold is more than 4 in the month of Nov-2022
run("""
SELECT *
FROM retail_sales
WHERE category = 'Clothing'
  AND strftime('%Y-%m', sale_date) = '2022-11'
  AND quantity >= 4
""", retail)

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantity,price_per_unit,cogs,total_sale
0,1484,2022-11-23,09:29:00,22,Female,19.0,Clothing,4.0,300.0,147.0,1200.0
1,64,2022-11-15,06:34:00,7,Male,49.0,Clothing,4.0,25.0,8.5,100.0
2,284,2022-11-12,09:17:00,129,Male,43.0,Clothing,4.0,50.0,20.5,200.0
3,1885,2022-11-09,07:32:00,148,Female,52.0,Clothing,4.0,30.0,10.8,120.0
4,547,2022-11-14,07:36:00,3,Male,63.0,Clothing,4.0,500.0,250.0,2000.0
5,159,2022-11-10,21:30:00,42,Male,26.0,Clothing,4.0,50.0,23.5,200.0
6,699,2022-11-21,22:21:00,129,Female,37.0,Clothing,4.0,30.0,16.2,120.0
7,1259,2022-11-03,17:31:00,105,Female,45.0,Clothing,4.0,50.0,21.0,200.0
8,146,2022-11-10,22:01:00,74,Male,38.0,Clothing,4.0,50.0,49.0,200.0
9,1476,2022-11-11,22:27:00,130,Female,27.0,Clothing,4.0,500.0,555.0,2000.0
10,1296,2022-11-26,20:42:00,45,Female,22.0,Clothing,4.0,300.0,342.0,1200.0
11,1696,2022-11-21,17:59:00,24,Female,50.0,Clothing,4.0,50.0,55.0,200.0
12,1497,2022-11-19,21:44:00,109,Male,41.0,Clothing,4.0,30.0,32.4,120.0
13,735,2022-11-26,21:38:00,153,Female,64.0,Clothing,4.0,500.0,515.0,2000.0
14,943,2022-11-05,19:29:00,90,Female,57.0,Clothing,4.0,300.0,318.0,1200.0
15,965,2022-11-27,21:45:00,84,Male,22.0,Clothing,4.0,50.0,13.0,200.0
16,1615,2022-11-17,13:43:00,82,Female,61.0,Clothing,4.0,25.0,13.5,100.0

In [56]:
##Write a SQL query to calculate the total sales  for each category.
run("""SELECT
    category,
    SUM(total_sale) as net_sale,
    COUNT(*) as total_orders
FROM retail_sales
GROUP BY 1 """, retail)

      category  net_sale  total_orders
0       Beauty  286840.0           614
1     Clothing  311070.0           702
2  Electronics  313810.0           684

In [57]:
##Write a SQL query to find the average age of customers who purchased items from the 'Beauty' category.
run("""
SELECT ROUND(AVG(age), 2) AS avg_age
FROM retail_sales
WHERE category = 'Beauty'
""", retail)

   avg_age
0    40.41

In [58]:
##Write a SQL query to find all transactions where the total_sale is greater than 1000.
run("""
SELECT * FROM retail_sales
WHERE total_sale >1000

""" ,retail)

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantity,price_per_unit,cogs,total_sale
0,522,2022-07-09,11:00:00,52,Male,46.0,Beauty,3.0,500.0,145.0,1500.0
1,559,2022-12-12,10:48:00,5,Female,40.0,Clothing,4.0,300.0,84.0,1200.0
2,1522,2022-11-14,08:35:00,48,Male,46.0,Beauty,3.0,500.0,235.0,1500.0
3,1559,2022-08-20,07:40:00,49,Female,40.0,Clothing,4.0,300.0,144.0,1200.0
4,421,2022-04-08,08:43:00,66,Female,37.0,Clothing,3.0,500.0,235.0,1500.0
...,...,...,...,...,...,...,...,...,...,...,...
301,908,2022-10-30,14:47:00,64,Male,46.0,Beauty,4.0,300.0,81.0,1200.0
302,1805,2023-10-10,13:35:00,79,Female,30.0,Beauty,3.0,500.0,225.0,1500.0
303,1908,2023-12-17,12:34:00,93,Male,46.0,Beauty,4.0,300.0,87.0,1200.0
304,211,2022-09-12,14:02:00,54,Male,42.0,Beauty,3.0,500.0,235.0,1500.0
305,1211,2023-11-22,14:59:00,82,Male,42.0,Beauty,3.0,500.0,235.0,1500.0

In [59]:
## Write a SQL query to find the total number of transactions made by each gender in each category
run("""
SELECT
category,
gender,
 COUNT(*) as total_trans
FROM retail_sales
GROUP
    BY
    category,
    gender
ORDER BY 1

""", retail)

      category  gender  total_trans
0       Beauty  Female          332
1       Beauty    Male          282
2     Clothing  Female          348
3     Clothing    Male          354
4  Electronics  Female          340
5  Electronics    Male          344

In [60]:
##Write a SQL query to calculate the average sale for each month. Find out best selling month in each year
run("""
SELECT year, month, avg_sale
FROM (
    SELECT
        strftime('%Y', sale_date) AS year,
        strftime('%m', sale_date) AS month,
        ROUND(AVG(total_sale), 2) AS avg_sale,
        RANK() OVER (
            PARTITION BY strftime('%Y', sale_date)
            ORDER BY AVG(total_sale) DESC
        ) AS rnk
    FROM retail_sales
    GROUP BY year, month
) AS t
WHERE rnk = 1
""", retail)

   year month  avg_sale
0  2022    07    541.34
1  2023    02    535.53

In [67]:
##Write a SQL query to find the top 5 customers based on the highest total sales
run("""
SELECT
    customer_id,
    SUM(total_sale) AS total_sales
FROM retail_sales
GROUP BY customer_id
ORDER BY total_sales DESC
LIMIT 5
""" , retail)

   customer_id  total_sales
0            3      38440.0
1            1      30750.0
2            5      30405.0
3            2      25295.0
4            4      23580.0

In [74]:
##Write a SQL query to find the number of unique customers who purchased items from each category.
run("""
SELECT
category,
COUNT(DISTINCT customer_id ) as unique_cs
FROM retail_sales
GROUP BY category
""" ,retail)

      category  unique_cs
0       Beauty        141
1     Clothing        149
2  Electronics        144

In [75]:
##Write a SQL query to create each shift and number of orders (Example Morning <12, Afternoon Between 12 & 17, Evening >17)
run("""
SELECT
    CASE
        WHEN CAST(strftime('%H', sale_time) AS INTEGER) < 12 THEN 'Morning'
        WHEN CAST(strftime('%H', sale_time) AS INTEGER) BETWEEN 12 AND 17 THEN 'Afternoon'
        ELSE 'Evening'
    END AS shift,
    COUNT(*) AS num_orders
FROM retail_sales
GROUP BY shift
""", retail)

       shift  num_orders
0  Afternoon         377
1    Evening        1062
2    Morning         561